# verify that all three testing methods work

steps:
- id: 'Docker Compose'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'builds', 
      'submit',
      '--config=cloudbuild.compose.yaml',
      '.'
  ]
  waitFor: ['-']

- id: 'GKE staging cluster'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'builds', 
      'submit',
      '--config=cloudbuild.gke.yaml',
      '.'
  ]
  waitFor: ['-']

- id: 'Single-node Kubernetes'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
      'builds', 
      'submit',
      '--config=cloudbuild.vm.yaml',
      '.'
  ]
  waitFor: ['-']

timeout:
  3600s
