apiVersion: v1
kind: Service
metadata:
  name: cookieshop-db
  labels:
    app: cookieshop
    role: db
spec:
  type: NodePort
  ports:
  - name: cookieshop-db
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: cookieshop