# pod for build, test, dockerize of Node web app

apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: node:10
    command: ['cat']
    tty: true
    volumeMounts:
      - name: workspace
        mountPath: '/workspace'
  # - name: kaniko
  #   image: gcr.io/kaniko-project/executor:v0.10.0
  #   volumeMounts:
  #     - name: kaniko-secret
  #       mountPath: /secret
  #     - name: workspace
  #       mountPath: '/workspace'
  #   env:
  #     - name: GOOGLE_APPLICATION_CREDENTIALS
  #       value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
  - name: workspace
    emptyDir: {}