# pod for provisioning and deploying test infra via docker-compose

apiVersion: v1
kind: Pod
metadata:
  name: compose-pod
spec:
  containers:
  - name: docker
    image: docker/compose:1.24.1
    command: ['cat']
    tty: true
    volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: docker-socket-volume
        mountPath: /var/run/docker.sock
    securityContext:
      privileged: true  # not good practice! kaniko is better!
  - name: gcloud
    image: google/cloud-sdk:slim
    command: ['cat']
    tty: true
    volumeMounts:
      - name: workspace
        mountPath: /workspace
  volumes:
    - name: workspace
      emptyDir: {}
      volumes:  
    - name: docker-socket-volume  
      hostPath:
        path: /var/run/docker.sock
        type: File