# pod for provisioning and deploying test infra via docker-compose

apiVersion: v1
kind: Pod
metadata:
  name: compose-pod
spec:
  containers:
  - name: kompose
    image: femtopixel/kompose # kompose will be installed at run; TODO: pre-bake image
    command: ['cat']
    tty: true
    volumeMounts:
      - name: workspace
        mountPath: /workspace
      - name: kaniko-secret
        mountPath: /secret
  restartPolicy: Never
  volumes:
    - name: workspace
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret